name: generate rss

on:
  schedule:
    - cron: '0 */12 * * *'
on:
  workflow_dispatch:
  
concurrency:
  group: rss
  cancel-in-progress: true
  
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - run: sudo apt-get update
      - run: sudo apt-get install -y fonts-ipafont
      - run: pip install -r requirements.txt
      - run: python generate.py

      - name: commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "update rss" || echo "no changes"

          # git pull --rebase origin main
          git push --force origin main
